version: "3"
services:
 app:
   container_name: montibragadin_app
   build: .
   command: node app.js
   ports:
     - "3000:3000"
   links:
     - "mongo:mongosrv"
 mongo:
   container_name: mongo_montibragadin_app
   image: mongo
   environment:
      MONGO_INITDB_DATABASE: auction_house
   volumes:
     - ./data:/data/db
     - ./app/utilities/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
   ports:
     - '27017:27017'
